package entity;

import java.io.Serializable;

/**
 * Model class of 绠＄悊鍛�.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Admin implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** 鐢ㄦ埛鍚�. */
	private String name;

	/** 瀵嗙爜. */
	private String password;

	/** 鐪熷疄濮撳悕. */
	private String realName;

	/**
	 * Constructor.
	 */
	public Admin() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 鐢ㄦ埛鍚�.
	 * 
	 * @param name
	 *            鐢ㄦ埛鍚�
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 鐢ㄦ埛鍚�.
	 * 
	 * @return 鐢ㄦ埛鍚�
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 瀵嗙爜.
	 * 
	 * @param password
	 *            瀵嗙爜
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 瀵嗙爜.
	 * 
	 * @return 瀵嗙爜
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 鐪熷疄濮撳悕.
	 * 
	 * @param realName
	 *            鐪熷疄濮撳悕
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * Get the 鐪熷疄濮撳悕.
	 * 
	 * @return 鐪熷疄濮撳悕
	 */
	public String getRealName() {
		return this.realName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Admin other = (Admin) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Admin [id=" + id + ", name=" + name + ", password=" + password + ", realName=" + realName + "]";
    }

}

