package entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 订单.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** 客户. */
	private Customer customer;

	/** The set of 订单条目. */
	private Set<OrderItem> orderItemSet;

	/**
	 * Constructor.
	 */
	public Orders() {
		this.orderItemSet = new HashSet<OrderItem>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 客户.
	 * 
	 * @param customer
	 *            客户
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * Get the 客户.
	 * 
	 * @return 客户
	 */
	public Customer getCustomer() {
		return this.customer;
	}

	/**
	 * Set the set of the 订单条目.
	 * 
	 * @param orderItemSet
	 *            The set of 订单条目
	 */
	public void setOrderItemSet(Set<OrderItem> orderItemSet) {
		this.orderItemSet = orderItemSet;
	}

	/**
	 * Add the 订单条目.
	 * 
	 * @param orderItem
	 *            订单条目
	 */
	public void addOrderItem(OrderItem orderItem) {
		this.orderItemSet.add(orderItem);
	}

	/**
	 * Get the set of the 订单条目.
	 * 
	 * @return The set of 订单条目
	 */
	public Set<OrderItem> getOrderItemSet() {
		return this.orderItemSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
