package entity;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 商品.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** 名称. */
	private String name;

	/** 价格. */
	private Float price;

	/** 数量. */
	private Long quantity;

	/** 描述. */
	private String description;

	/** 商品分类. */
	private ProductCategory productCategory;

	/** The set of 商品图片. */
	private Set<ProductPicture> productPictureSet;
	/**
	 * 默认的一张图片
	 */
	private String defaultPicture;

	/**
	 * Constructor.
	 */
	public Product() {
		this.productPictureSet = new HashSet<ProductPicture>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 名称.
	 * 
	 * @param name
	 *            名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 名称.
	 * 
	 * @return 名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 价格.
	 * 
	 * @param price
	 *            价格
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * Get the 价格.
	 * 
	 * @return 价格
	 */
	public Float getPrice() {
		return this.price;
	}

	/**
	 * Set the 数量.
	 * 
	 * @param quantity
	 *            数量
	 */
	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	/**
	 * Get the 数量.
	 * 
	 * @return 数量
	 */
	public Long getQuantity() {
		return this.quantity;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param description
	 *            描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 商品分类.
	 * 
	 * @param productCategory
	 *            商品分类
	 */
	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	/**
	 * Get the 商品分类.
	 * 
	 * @return 商品分类
	 */
	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	/**
	 * Set the set of the 商品图片.
	 * 
	 * @param productPictureSet
	 *            The set of 商品图片
	 */
	public void setProductPictureSet(Set<ProductPicture> productPictureSet) {
		this.productPictureSet = productPictureSet;
	}

	/**
	 * Add the 商品图片.
	 * 
	 * @param productPicture
	 *            商品图片
	 */
	public void addProductPicture(ProductPicture productPicture) {
		this.productPictureSet.add(productPicture);
	}

	/**
	 * Get the set of the 商品图片.
	 * 
	 * @return The set of 商品图片
	 */
	public Set<ProductPicture> getProductPictureSet() {
		return this.productPictureSet;
	}

	/**
     * @return the defaultPicture
     */
    public String getDefaultPicture() {
        return defaultPicture;
    }

    /**
     * @param defaultPicture the defaultPicture to set
     */
    public void setDefaultPicture(String defaultPicture) {
        this.defaultPicture = defaultPicture;
    }

    /**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
