package entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 商品分类.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductCategory implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** 类别名. */
	private String name;

	/** 分级. */
	private Integer level;

	/** 父类别的id. */
	private Long productCategoryId;
	/**父类别名*/
	private String superName;
	/**子分类**/
	private Set<ProductCategory> subCategorys = new HashSet<>();

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 类别名.
	 * 
	 * @param name
	 *            类别名
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 类别名.
	 * 
	 * @return 类别名
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 分级.
	 * 
	 * @param level
	 *            分级
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * Get the 分级.
	 * 
	 * @return 分级
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * Set the 父类别的id.
	 * 
	 * @param productCategoryId
	 *            父类别的id
	 */
	public void setProductCategoryId(Long productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	/**
	 * Get the 父类别的id.
	 * 
	 * @return 父类别的id
	 */
	public Long getProductCategoryId() {
		return this.productCategoryId;
	}

	/**
     * @return the superName
     */
    public String getSuperName() {
        return superName;
    }

    /**
     * @param superName the superName to set
     */
    public void setSuperName(String superName) {
        this.superName = superName;
    }

    /**
     * @return the subCategorys
     */
    public Set<ProductCategory> getSubCategorys() {
        return subCategorys;
    }

    /**
     * @param subCategorys the subCategorys to set
     */
    public void setSubCategorys(Set<ProductCategory> subCategorys) {
        this.subCategorys = subCategorys;
    }

    /**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductCategory other = (ProductCategory) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
